[{
	"id":0,
	"text":"销售",
	"children":[{
		"id":1,
		"text":"新建",
		"children":[{
			"id":101,
			"text":"销售订单",
			"href":"content.html",
			"iconCls":"icon-GetExternalDataFromText"
		},{
			"id":102,
			"text":"销售出库单",
			"href":"ribbon.html",
			"iconCls":"icon-GetExternalDataFromText"
		},{
			"id":103,
			"text":"销售退货单",
			"href":"datagrid23_demo.html",
			"iconCls":"icon-GetExternalDataFromText"
		}]
	},{
		"id":2,
		"text":"打开",
		"children":[{
			"id":104,
			"text":"销售订单",
			"href":"texteditor.html",
			"iconCls":"icon-WindowsSwitch"
		},{
			"id":105,
			"text":"销售出库单",
			"href":"content.html",
			"iconCls":"icon-WindowsSwitch"
		},{
			"id":106,
			"text":"销售退货单",
			"href":"public.html",
			"iconCls":"icon-WindowsSwitch"
		}]
	},{
		"id":3,
		"text":"查询",
		"children":[{
			"id":107,
			"text":"销售订单查询",
			"href":"DataGridVirtualScroll.html",
			"iconCls":"icon-ChartEditDataSource"
		},{
			"id":108,
			"text":"销售出库单查询",
			"href":"public.html",
			"iconCls":"icon-ChartEditDataSource"
		},{
			"id":109,
			"text":"销售退货单查询",
			"href":"public.html",
			"iconCls":"icon-ChartEditDataSource"
		},{
			"id":110,
			"text":"销售汇总查询",
			"href":"LargeData.html",
			"iconCls":"icon-ChartEditDataSource"
		}]
	}]
},{
	"id":16,
	"text":"基本资料",
	"children":[{
		"id":1701,
		"text":"产品类型",
		"mode":"productclass",
		"style":"productclass",
		"template":1,
		"href":"client/SimpChinese/bi/"
	},{
		"id":1702,
		"text":"产品目录",
		"mode":"product",
		"style":"product",
		"edit":"product",
		"template":2,
		"href":"client/SimpChinese/bi/"
	},{
		"id":1703,
		"text":"仓库",
		"mode":"stock",
		"style":"stock",
		"template":3,
		"href":"client/SimpChinese/bi/"
	}]
},{
	"text":"用户和权限",
	"state":"closed",
	"children":[{
		"id":1804,
		"text":"用户设置",
		"href":"public.html"
	},{
		"id":1805,
		"text":"操作授权",
		"href":"public.html"
	},{
		"id":1806,
		"text":"仓库授权",
		"href":"public.html"
	},{
		"id":1807,
		"text":"区域授权",
		"href":"public.html"
	},{
		"id":1809,
		"text":"部门授权",
		"href":"public.html"
	},{
		"id":1810,
		"text":"角色授权",
		"href":"public.html"
	}]
},{
	"id":18,
	"text":"系统设置",
	"state":"closed",
	"children":[{
		"text":"配置工具",
		"children":[{
			"id":1811,
			"text":"菜单",
			"href":"public.html"
		},{
			"id":1812,
			"text":"菜单组",
			"href":"public.html"
		},{
			"id":1801,
			"text":"显示式样",
			"href":"public.html"
		},{
			"id":1802,
			"text":"查询设计",
			"href":"public.html"
		},{
			"id":1803,
			"text":"查询模板",
			"href":"public.html"
		}]
	}]
}]
